// Apps  2 tiers/app2-contacts/frontend/src/App.vue
<template>
  <div class="container">
    <h1>📇 Carnet de Contacts</h1>
    <p>{{ status }}</p>
    <form @submit.prevent="addContact">
      <input v-model="name" placeholder="Nom" required />
      <input v-model="phone" placeholder="Téléphone" />
      <input v-model="email" placeholder="Email" />
      <button type="submit">Ajouter</button>
    </form>
    <ul>
      <li v-for="c in contacts" :key="c.id">
        <strong>{{ c.name }}</strong>
        <span v-if="c.phone"> — {{ c.phone }}</span>
        <span v-if="c.email"> — {{ c.email }}</span>
        <button @click="deleteContact(c.id)">🗑️</button>
      </li>
    </ul>
  </div>
</template>

<script>
const API_URL = 'http://localhost:5000/api';

export default {
  data() {
    return {
      contacts: [],
      name: '',
      phone: '',
      email: '',
      status: 'Connexion au backend...'
    };
  },
  mounted() {
    // Vérification de la communication frontend <-> backend
    fetch(`${API_URL}/health`)
      .then((res) => res.json())
      .then((data) => {
        this.status = `✅ ${data.message}`;
      })
      .catch(() => {
        this.status = "❌ Backend inaccessible. Vérifiez qu'il est démarré sur le port 5000.";
      });
    this.fetchContacts();
  },
  methods: {
    fetchContacts() {
      fetch(`${API_URL}/contacts`)
        .then((res) => res.json())
        .then((data) => {
          this.contacts = data;
        });
    },
    addContact() {
      fetch(`${API_URL}/contacts`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: this.name, phone: this.phone, email: this.email })
      })
        .then((res) => res.json())
        .then(() => {
          this.name = '';
          this.phone = '';
          this.email = '';
          this.fetchContacts();
        });
    },
    deleteContact(id) {
      fetch(`${API_URL}/contacts/${id}`, { method: 'DELETE' }).then(this.fetchContacts);
    }
  }
};
</script>

<style scoped>
.container {
  max-width: 500px;
  margin: 40px auto;
  font-family: sans-serif;
}
form {
  display: flex;
  gap: 8px;
  margin-bottom: 16px;
  flex-wrap: wrap;
}
input {
  padding: 8px;
  flex: 1;
  min-width: 100px;
}
ul {
  list-style: none;
  padding: 0;
}
li {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 0;
  border-bottom: 1px solid #eee;
}
li strong {
  flex: 0 0 auto;
}
li span {
  flex: 1;
}
</style>

// Apps  2 tiers/app1-todo/frontend/src/App.jsx
import { useState, useEffect } from 'react';

const API_URL = 'http://localhost:3001/api';

function App() {
  const [todos, setTodos] = useState([]);
  const [text, setText] = useState('');
  const [status, setStatus] = useState('Connexion au backend...');

  useEffect(() => {
    // Vérification de la communication frontend <-> backend
    fetch(`${API_URL}/health`)
      .then((res) => res.json())
      .then((data) => setStatus(`✅ ${data.message}`))
      .catch(() => setStatus("❌ Backend inaccessible. Vérifiez qu'il est démarré sur le port 3001."));
    fetchTodos();
  }, []);

  const fetchTodos = () => {
    fetch(`${API_URL}/todos`)
      .then((res) => res.json())
      .then(setTodos)
      .catch((err) => console.error(err));
  };

  const addTodo = (e) => {
    e.preventDefault();
    if (!text.trim()) return;
    fetch(`${API_URL}/todos`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text })
    })
      .then((res) => res.json())
      .then(() => {
        setText('');
        fetchTodos();
      });
  };

  const toggleTodo = (id) => {
    fetch(`${API_URL}/todos/${id}`, { method: 'PUT' }).then(fetchTodos);
  };

  const deleteTodo = (id) => {
    fetch(`${API_URL}/todos/${id}`, { method: 'DELETE' }).then(fetchTodos);
  };

  return (
    <div style={{ maxWidth: 500, margin: '40px auto', fontFamily: 'sans-serif' }}>
      <h1>📝 Gestion de Tâches</h1>
      <p>{status}</p>
      <form onSubmit={addTodo} style={{ display: 'flex', gap: 8 }}>
        <input
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Nouvelle tâche..."
          style={{ flex: 1, padding: 8 }}
        />
        <button type="submit">Ajouter</button>
      </form>
      <ul style={{ listStyle: 'none', padding: 0 }}>
        {todos.map((todo) => (
          <li
            key={todo.id}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              padding: '8px 0',
              borderBottom: '1px solid #eee'
            }}
          >
            <input type="checkbox" checked={!!todo.done} onChange={() => toggleTodo(todo.id)} />
            <span style={{ flex: 1, textDecoration: todo.done ? 'line-through' : 'none' }}>
              {todo.text}
            </span>
            <button onClick={() => deleteTodo(todo.id)}>🗑️</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;
